# .github/workflows/semantic-release.yml
name: Create Tag

on:
  push:
    branches:
      - main

permissions:
  contents: write # Required to push the new tag

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Go Semantic Release
        uses: go-semantic-release/action@v1
        with:
          # This is the crucial change:
          # We tell the action to ONLY create and push a tag.
          # It will NOT create a GitHub release.
          create-release: "false"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
